### ISSUE TITLE
Make Twitter feed more obvious

### ISSUE THREAD

**Issue by petdance** [hashrocket/hr-til#111]
I love the TIL blog, so was extra pleased to find that it has a Twitter account.  I'd suggest putting it  right up front on the page where you can't miss it, in addition to under the question mark icon.

**Comment by jwworth** [comment]
I like this idea; thank you! Our Twitter follower count is low compared with general site engagement, so this could help.

I'll run this by some design folks and see what we can come up with.

**Comment by jwworth** [comment]
Thanks for the feedback @petdance, and thanks @ryenotbread for the design. Deployed to production!
