### ISSUE TITLE
Default Channels for Open-Sourcing

### ISSUE THREAD

**Issue by jbranchaud** [hashrocket/hr-til#12]
I'm wondering if the open-source version of this application should have default channels. If so, what should those be. If not (I'm more in this camp), then how to we abstract it out and also provide instructions for channel setup for folks deploying their own.

This is the relevant code: https://github.com/hashrocket/hr-til/blob/master/db/seeds.rb#L1-L2

**Comment by jwworth** [comment]
@jbranchaud I can work on this, unless you'd like to. I'm proposing a README block explaining how to change the default channels for your setup (by editing the seed file). I'd like to keep our default channels if/when we need to setup a new Hashrocket TIL instance in the future.
