### ISSUE TITLE
Plans for a feed (RSS, atom, etc)?

### ISSUE THREAD

**Issue by jgdavey** [hashrocket/hr-til#128]
Because I like both TIL and my feed reader. :-)

**Comment by tmock12** [comment]
Hi Mr. Davey 😄 

I know we currently have one for the Elixir TIL (https://github.com/hashrocket/tilex) You can find our Hashrocket one here - http://til.hashrocket.com/rss 

Looks like the Rails TIL here (hr-til) is missing an RSS feed. I'll leave this open in case someone wants to implement it.

Hope all is well! Miss you!

**Comment by jwworth** [comment]
Thanks for the issue, Josh! 👍 

We built an atom feed for the Rails app, which is still publicly available: https://hr-til-production.herokuapp.com/?format=atom. It doesn't explicitly support RSS, so some readers may not be able to detect it.

As @tmock12 mentioned, the Phoenix app currently in production supports `/rss` and `?format=atom`, with an autodetect header. @jgdavey if you're reader isn't detecting our feed that would definitely be a bug worth fixing.

**Comment by jgdavey** [comment]
Aha, I see. I suppose it might be nice to add a `rel="alternate"` link to the head of the HTML for autodiscovery.

Cheers!

**Comment by jwworth** [comment]
Thanks for checking in, Josh! :)
