### ISSUE TITLE
bundle fails

### ISSUE THREAD

**Issue by clemensp** [hashrocket/hr-til#13]
Hello,

Yesterday, I tried setting up the blog, and bundling fails out of the box:

```
❯ bundle
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.5.0
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'mini_portile'
```

I am using bundler version 1.11.2.

Personally, I got past the issue by removing Gemfile.lock, and running `bundle`, but it's obviously not the right fix for this issue.

I started with a clean slate for gems, since I did not have ruby 2.3.0 installed (which the project currently asks for).

I figure you guys would have a better idea of how to update the lock file rather than me!

Let me know if you need any more information.
Cheers!

**Comment by jbranchaud** [comment]
@clemensp Thanks for letting us know about this.

It would be helpful if you could give us more details about your environment so that we can attempt to reproduce and fix this. Operating System? RVM version? etc.

**Comment by clemensp** [comment]
@jbranchaud Thanks for the quick reply!  Here's some more info:

OS: OSX Yosemite 10.10.5
RVM: 1.26.11

I'm currently on SHA 606950c.

I did the following to reproduce it again:

1. `git checkout Gemfile.lock` (I had an updated version, which I got by blowing away Gemfile.lock and running `bundle`)
1. run `bundle`

I didn't have to blow away any gems to reproduce the issue.

**Comment by jbranchaud** [comment]
@clemensp what are the difference in the `Gemfile.lock

**Comment by jwworth** [comment]
@clemensp thanks for reporting. I believe a dependency was lost when I merged the `open-source` branch into master. I think it's fixed with 3e6f7cd6314e420d51aedd0cb0400de1b789e0f8.

Please try pulling the latest changes and running `bundle install` again with the latest Gemfile.lock.

**Comment by clemensp** [comment]
@jbranchaud  Good question.  Also, please excuse my slow response time.  I'm at a library with a shitty connection at the moment, so running bundle takes forever and many attempts.  -.-

Of all the differences, looks like this is the one causing the problem:

```
+    mini_portile2 (2.0.0)
<snip>
-    nokogiri (1.6.6.2)
-      mini_portile (~> 0.6.0)
+    nokogiri (1.6.7.2)
+      mini_portile2 (~> 2.0.0.rc2)
```

Essentially, mini_portile is listed as a dependency of nokogiri, but not listed in the GEM list under specs.

I tried adding `mini_portile (~> 0.6.0)` directly to the lock file in the GEM section under `minitest (5.8.3)`, but it causes bundler to fail with:

```
Your lockfile is unreadable. Run `rm Gemfile.lock` and then `bundle install` to generate a new lockfile.
```

However, when I added `mini_portile (~> 0.6.0)` in the DEPENDENCIES section under `launchy`, it bundled successfully.

The above fix is probably less desirable since it involves editing a generated file.

Another fix that worked was to update nokogiri in the bundle:
`bundle update nokogiri`

That fixes the lock file (at least for me).

**Comment by clemensp** [comment]
@jwworth I can confirm that `bundle install` works successfully in the latest commit.  :)

If you're interested in a less gem-risk move, `bundle update nokogiri` works as well.  :D

**Comment by jwworth** [comment]
Excellent. Thanks for reporting! Closing this issue.
