### ISSUE TITLE
Error in oauth, jwt 'decode' issue

### ISSUE THREAD

**Issue by inexion** [hashrocket/hr-til#22]
Also just tried changing over my authorized domains to my own, generated an API key at the Google dev console, and got this error: 

`JWT::InvalidIatError`
`Invalid iat`
              
    end
    if options[:verify_iat] && payload.include?('iat')
      fail JWT::InvalidIatError.new('Invalid iat') unless payload['iat'].is_a?(Integer) && payload['iat'].to_i <= Time.now.to_i
    end
    if options[:verify_aud] && options['aud']
      if payload['aud'].is_a?(Array)

`jwt (1.5.1) lib/jwt.rb:170:in decode'`
`omniauth-google-oauth2 (0.3.1) lib/omniauth/strategies/google_oauth2.rb:61:in block in <class:GoogleOauth2>'`

Looks like you can disable `jwt`, by going in `config/initializers/omniauth.rb` and adding:
`skip_jwt: true`

This allowed me to login.

**Comment by jwworth** [comment]
Thanks for the report. We have not seen this before.

It looks like `skip_jwt` skips processing related to the `iat` field, which Google describes as:

> The time the ID token was issued, represented in Unix time (integer seconds).
https://developers.google.com/identity/protocols/OpenIDConnect

Would you be able to tell us more about how you reproduced the error after acquiring the token, including Ruby version, Rails version, and operating system?
