### ISSUE TITLE
HTML <code> tag and overflow

### ISSUE THREAD

**Issue by jwgoh** [hashrocket/hr-til#25]
![screenshot from 2016-02-23 01 14 05](https://cloud.githubusercontent.com/assets/6704206/13226106/c72ad070-d9ca-11e5-9f5f-46a7256029b3.png)

The horizontal scroll bar for a code block (when the content overflows) does not work. Setting `overflow: scroll` seems to fix this although the scroll bar would now always show.

It seems to only affect Chrome. I am using Version 48.0.2564.116 (64-bit) on Mac OS X.

**Comment by jwworth** [comment]
Thanks for the report! We've seen this before. It seems to be a really specific bug. I have the same version of Chrome (Version 48.0.2564.116 (64-bit)) installed on Mac OS X and I don't have the issue. Has never been an issue on Firefox.

Would like to keep the hidden scroll bar if possible.

**Comment by jwgoh** [comment]
The scroll bar also does not work on my Ubuntu machine with Google Chrome (Version 48.0.2564.116 (64-bit)). All good on Firefox.
Any ideas why this might be happening? Very weird

**Comment by jwworth** [comment]
Not sure why this is happening, and I can't reproduce it with my setup. Would love for somebody to solve it, while maintaining the hidden scrollbar effect.

**Comment by jwworth** [comment]
TIL has undergone a total design overhaul since this issue was reported. Can anybody still reproduce it?

**Comment by jwgoh** [comment]
I can now scroll (!)  but the scrollbar is hidden on my Mac. This seems to be a problem for OSX trackpad users in Webkit.

<img width="709" alt="screen shot 2016-03-17 at 12 05 05 am" src="https://cloud.githubusercontent.com/assets/6704206/13819283/f58fdf80-ebd3-11e5-9270-c67b68591f52.png">

**Comment by jwworth** [comment]
@jwgoh is the scroll bar hidden *while* scrolling, i.e. using the arrow keys, or is it only hidden the rest of the time? As I understand it, the first case would be a bug, but the second would be desired behavior (the scroll bar should disappear when not scrolling).

**Comment by jwgoh** [comment]
It was the first case as far as I remember i.e. scrollbar is hidden _while_ scrolling.

But it seems to be working fine now on Safari albeit a bit hard to see because the scrollbar colour is almost the same as the background colour for code block.

Either something has changed to fix this or my eyesight needs fixing! 👓
