### ISSUE TITLE
No way to delete posts or drafts

### ISSUE THREAD

**Issue by hvoIIITA** [hashrocket/hr-til#31]
First of all, I would like to say thanks for this! I've always had a passing interest in web development, but I never really had a chance to really dig into the nuts and bolts. When I discovered your stuff on a post in Hacker News, I really wanted to explore it.

One thing I've noticed, though, is that there doesn't seem to be any way to delete posts or drafts. Don't see it in the features list either. Is this something just not yet implemented? Just wondering if this is something that I could really dig into solving (baby steps :+1:), or if its by design.

**Comment by jwworth** [comment]
Thanks for the feedback!

Not allowing users to delete posts was a deliberate design choice. We wanted people to post quickly about whatever they had learned, and not have the ability to alter that history. The fact that an older revelation may seem trivial or contradictory compared to what you're learning today is kind of the whole point of TIL. Everybody is learning, and everybody was a beginner once.

Feel free to delete posts through the database, or implement on your own delete functionality. But I think this is one of the best (though occasionally frustrating) features of TIL, so we plan to keep it.

**Comment by hvoIIITA** [comment]
I understand the sentiment. I figured with the word limit and how easy it is to publish a snippet that you wanted a quick pace with these knowledge tidbits. The only issue I have is that if you'e like me, the cluttering of half-created drafts will annoy you!

As this is an intended feature, then there is no real reason to keep it open.
