### ISSUE TITLE
til.hashrocket.com is hardcoded in config/environments/production.rb

### ISSUE THREAD

**Issue by leejunkit** [hashrocket/hr-til#35]
This causes the app to redirect back to `til.hashrocket.com` upon saving an edited post.

**Comment by jwworth** [comment]
Thanks for the report.

This is an important feature to our instance of Today I Learned. If we removed it, Rails wouldn't know where to redirect to after saving.

If not hard coded, how would you suggest we implement this feature?

**Comment by leejunkit** [comment]
For our own install we simply removed it and left it as an empty hash:
```
config.action_controller.default_url_options = {}
```
Everything still seems to work fine in my quick testing. I'm not too familiar with Rails so I'm wondering how come we needed to explicitly set the host in the app - won't this make it hard to deploy to whichever host we wanted to?

**Comment by jwworth** [comment]
This is a good point. Deploying to multiple hosts has not been a use case for us, but it could be for others.

There are tests that rely on a host and protocol being set, but I believe they may be getting set in more than one place. The URL could certainly be inferred using other methods.

I'd like to take this on as a refactor in the next few weeks, if nobody else is interested. Your workaround sounds good and I hope that it can suffice in the meantime.

**Comment by jwworth** [comment]
@leejunkit we just merged https://github.com/hashrocket/hr-til/pull/39, which hopefully addresses this issue. Knowing the host and protocol is important for some of the social features; ideally this preserves that functionality for us while making the app more portable for you and others.

**Comment by leejunkit** [comment]
Hello, thank you for that! Just deployed it on our end and it works fine. :) We don't mind storing the host and protocol in the env vars, it's a tradeoff we are okay with. 

Thanks for open-sourcing this by the way, it is helping our developers to share knowledge that sometimes aren't worth writing a formal blog post. And also for following up on issues like these too!

**Comment by jwworth** [comment]
Glad to hear! Thanks for using the project and providing this feedback. :+1:
