### ISSUE TITLE
Include title and author in markdown response

### ISSUE THREAD

**Issue by jbranchaud** [hashrocket/hr-til#48]
The markdown response for the post show only sends the markdown body. Perhaps we can prepend the title and author to this as well. \cc @jgdavey

**Comment by jwworth** [comment]
👍 I've wanted this for a while. I can take care of it.

**Comment by vnegrisolo** [comment]
@jwworth does the related PR closes this issue?

**Comment by jwworth** [comment]
Yes, and it is now deployed to production.
