### ISSUE TITLE
Display syntax type on code snippets

### ISSUE THREAD

**Issue by vnegrisolo** [hashrocket/hr-til#52]
We should display the syntax type used on code snippets so the user can identify it faster.

So if a contributor type:

    ```javascript
    var x = true;
    x ? 'yes' : 'no'
    //=> "yes"
    x = false;
    x ? 'yes' : 'no'
    //=> "no"
    ```

We could add `javascript` as a hint to following:

<img width="545" alt="screen shot 2016-06-02 at 7 12 08 am" src="https://cloud.githubusercontent.com/assets/1071893/15743273/3cbba66e-2892-11e6-8dac-dc093f3e42f1.png">

By the way this is the generated html for that block:

<img width="272" alt="screen shot 2016-06-02 at 7 11 11 am" src="https://cloud.githubusercontent.com/assets/1071893/15743282/4ded13dc-2892-11e6-8b26-c9ab6ba4dc83.png">

## reference

On [Ember documentation](https://guides.emberjs.com/v2.5.0/controllers/):

<img width="754" alt="screen shot 2016-06-02 at 7 12 27 am" src="https://cloud.githubusercontent.com/assets/1071893/15743274/3cc099a8-2892-11e6-9b39-86336b4d3ded.png">

**Comment by jwworth** [comment]
Great idea! 👍 I've entered this as the following Pivotal story:

https://www.pivotaltracker.com/story/show/120771107

**Comment by jwworth** [comment]
Closing via attached pull request.
