### ISSUE TITLE
RecordNotFound error in authors/username

### ISSUE THREAD

**Issue by murjax** [hashrocket/hr-til#83]
When requesting `authors/username`, I receive a RecordNotFound error starting that the requested `Developer` could not be found. This seems to only occur when the `Developer` username contains a `.`, (e.g. "john.smith"). Should these types of usernames simply not be allowed to exist or should they be accommodated in some way?

**Comment by jwworth** [comment]
Interesting; nice catch! 👍 

I think they should not be allowed. In our UI, the only way to create a user is through the sessions controller, based off attributes coming from Google. Google usernames allow characters that should not be part of a URL:

> Usernames can contain letters (a-z), numbers (0-9), dashes (-), underscores (_), apostrophes ('}, and periods (.).

Source: https://support.google.com/a/answer/33386?hl=en

Most Google usernames become TIL usernames like `johndoe`, and I like that pattern. I would lean toward removing anything not alphanumeric from the username.

Not sure if this would affect many users. It seems like a definite edge case based off Hashrocket's production experience so far.
